name: Rocket
description: 'Installs the Rocket starter module set, theme, and reusable baseline configuration.'
type: Site

install:
  - admin_toolbar
  - admin_toolbar_tools
  - block
  - bootstrap5
  - captcha
  - crop
  - field
  - file
  - filter
  - focal_point
  - image
  - image_effects
  - key
  - layout_builder
  - layout_discovery
  - mailsystem
  - media
  - menu_link_content
  - menu_ui
  - metatag
  - metatag_favicons
  - metatag_open_graph
  - node
  - pathauto
  - path
  - redirect
  - responsive_image
  - rocket
  - schema_metatag
  - schema_web_site
  - sendgrid_integration
  - slick
  - slick_ui
  - slick_views
  - turnstile
  - text
  - views
  - views_bootstrap
  - webform
  - webform_ui
  - xmlsitemap

config:
  strict: false
  import:
    admin_toolbar: '*'
    admin_toolbar_tools: '*'
    blazy: '*'
    bootstrap5:
      - bootstrap5.settings
    captcha: '*'
    focal_point: '*'
    image_effects: '*'
    mailsystem: '*'
    metatag: '*'
    pathauto: '*'
    redirect:
      - redirect.settings
      - system.action.redirect_delete_action
      - views.view.redirect
    sendgrid_integration: '*'
    slick: '*'
    turnstile: '*'
    webform: '*'
    xmlsitemap:
      - xmlsitemap.settings
  actions:
    system.theme:
      simpleConfigUpdate:
        admin: claro
        default: rocket
    captcha.settings:
      simpleConfigUpdate:
        default_challenge: turnstile/Turnstile
        wrong_captcha_response_message: 'Please try again.'
    core.entity_view_display.node.page.default:
      enableLayoutBuilder: []
      allowLayoutOverrides: true
      setProperties:
        third_party_settings.layout_builder.sections:
          -
            layout_id: layout_onecol
            layout_settings:
              label: ''
            components:
              665ca6e5-f169-4dc8-a9ae-2622e2cc77f9:
                uuid: 665ca6e5-f169-4dc8-a9ae-2622e2cc77f9
                region: content
                configuration:
                  id: 'field_block:node:page:body'
                  label_display: '0'
                  context_mapping:
                    entity: layout_builder.entity
                  formatter:
                    type: text_default
                    label: hidden
                    settings: {  }
                    third_party_settings: {  }
                weight: 0
                additional: {  }
              64577024-9215-41e7-b675-d8c0e6f6c139:
                uuid: 64577024-9215-41e7-b675-d8c0e6f6c139
                region: content
                configuration:
                  id: 'extra_field_block:node:page:links'
                  label_display: '0'
                  context_mapping:
                    entity: layout_builder.entity
                weight: 1
                additional: {  }
            third_party_settings: {  }
        content: {  }
        hidden.layout_builder__layout: true
        hidden.body: true
        hidden.links: true
    node.type.page:
      setThirdPartySettings:
        -
          module: menu_ui
          key: available_menus
          value:
            - footer
            - main
        -
          module: menu_ui
          key: parent
          value: 'footer:'
    mailsystem.settings:
      simpleConfigUpdate:
        defaults:
          sender: sendgrid_integration
          formatter: sendgrid_integration
        modules:
          sendgrid_integration:
            none:
              sender: sendgrid_integration
              formatter: sendgrid_integration
    turnstile.settings:
      simpleConfigUpdate:
        widget:
          theme: light
          size: normal
          tabindex: 0
          language: auto
          retry: auto
          retry_interval: 8000
          appearance: always
    user.role.authenticated:
      grantPermissions:
        - 'access comments'
        - 'access shortcuts'
        - 'post comments'
        - 'search content'
        - 'skip comment approval'
        - 'use text format basic_html'
        - 'use text format webform_default'
        - 'view media'
    user.role.content_editor:
      grantPermissions:
        - 'access administration pages'
        - 'view own unpublished content'
